name: syncfusion_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.2
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  desktop_window: 0.4.0
  syncfusion_localizations: ^20.1.47
  syncfusion_flutter_datagrid_export: ^20.1.47-beta
  syncfusion_flutter_calendar: ^20.1.47
  syncfusion_flutter_datepicker: ^20.1.47
  syncfusion_flutter_charts: ^20.1.47
  syncfusion_flutter_gauges: ^20.1.47
  syncfusion_flutter_sliders: ^20.1.47
  syncfusion_flutter_pdf: ^20.1.47-beta
  syncfusion_flutter_barcodes: ^20.1.47
  syncfusion_officechart: ^20.1.47-beta
  syncfusion_flutter_maps: ^20.1.47
  syncfusion_flutter_signaturepad: ^20.1.47
  syncfusion_flutter_pdfviewer: ^20.1.47-beta
  syncfusion_flutter_treemap: ^20.1.47-beta

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
